services:
  walrus-test:
    build: .
    container_name: walrus-test
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=supabase_admin
      - PG_USER=supabase_admin
      - POSTGRES_DB=postgres
    volumes:
      - ./:/walrus
    # Keep container running if you want to debug
    # command: tail -f /dev/null
